version: "3.7"
services:
  vite_docker:
    image: oven/bun:1
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
    command: -c "bun  && bun run vite"
